import type {
  CinematicDefinition,
  CinematicPerformanceRequest,
} from './CinematicDefinition';

const performance = (
  cueId: string,
  shotId: string,
  participantId: string,
  targetParticipantId?: string,
  _targetMarkId?: string,
  intent: CinematicPerformanceRequest['intent'] = 'neutral-hold',
  atSeconds = 0,
): CinematicPerformanceRequest => ({
  cueId,
  shotId,
  atSeconds,
  participantId,
  intent,
  phase: 'start',
  targetParticipantId,
  missingPerformancePolicy: 'block',
  required: true,
});

export const cinematicDefinitions = [
  {
    id: 'cinematic.ash-001.opening',
    storyBeatId: 'ash-001-northbar-arrival',
    missionId: 'ash-001-walk-the-block',
    participantIds: ['casual', 'mack', 'della-voss'],
    speakerIds: ['rook', 'mack', 'della-voss'],
    entryEventId: 'cinematic.ash-001.northbar-arrival.entered',
    completionEventId: 'cinematic.ash-001.northbar-arrival.completed',
    skipPolicy: 'confirm',
    dependencies: {
      levelId: 'northbar-coach-depot',
      locationId: 'landmark.northbar-bay-two',
      cameraAnchorIds: [
        'camera.northbar.establish-bay-two',
        'camera.northbar.establish-bay-two-safe',
        'camera.northbar.rook-mack-two-shot',
        'camera.northbar.rook-mack-two-shot-safe',
        'camera.northbar.mack-missing-close',
        'camera.northbar.mack-missing-close-safe',
        'camera.northbar.della-carbon-close-safe',
        'camera.northbar.della-carbon-close-alt',
        'camera.northbar.three-way-cover',
        'camera.northbar.three-way-cover-safe',
        'camera.northbar.rook-decision-close-safe',
        'camera.northbar.rook-decision-close-alt',
        'camera.northbar.ticket-choice',
        'camera.northbar.ticket-choice-safe',
        'camera.northbar.wagon-entry',
        'camera.northbar.wagon-departure',
      ],
      assetIds: [
        'prop.northbar.arrival-manifest',
        'prop.northbar.manifest-carbon',
        'vehicle.northbar.intercity-coach',
        'vehicle.mack.service-wagon',
      ],
      animationIds: ['idle'],
      worldFactIds: [
        'orin-status',
        'rook-accepted-orin-search',
        'marrow-has-rook-arrival-time',
      ],
    },
    restorationPolicy: 'authoritative-destination',
    destination: {
      id: 'transition.ash-001.northbar-to-junction',
      levelId: 'test-district',
      locationId: 'landmark.north-approach',
      spawnId: 'spawn.player-default',
      cameraAnchorId: 'camera.ash-001.junction-arrival',
    },
    landingTransaction: {
      id: 'transaction.ash-001.northbar-arrival',
      storyEffectIds: [
        'story.ash-001.orin-missing-revealed',
        'story.ash-001.rook-chooses-junction',
        'story.ash-001.marrow-copies-arrival',
        'story.ash-001.rook-arrives-junction',
      ],
      missionHandoffIds: [
        'ash-001-arrival-prelude-complete',
        'ash-001-check-signal-corner',
      ],
    },
    participantFailurePolicy: 'land-at-destination',
    blocking: [
      {
        participantId: 'casual',
        markId: 'mark.northbar.rook-curb',
        facingParticipantId: 'mack',
        maximumDisplacementMetres: 0.2,
      },
      {
        participantId: 'mack',
        markId: 'mark.northbar.mack-pillar',
        facingParticipantId: 'casual',
        maximumDisplacementMetres: 0.2,
      },
      {
        participantId: 'della-voss',
        markId: 'mark.northbar.della-counter',
        facingParticipantId: 'mack',
        maximumDisplacementMetres: 0.2,
      },
    ],
    shots: [
      {
        id: 'shot.ash-001.northbar-establish',
        purpose:
          'Show Rook leaving the overnight coach while Mack and Della independently watch the arrival.',
        cameraAnchorId: 'camera.northbar.establish-bay-two',
        alternateCameraAnchorId: 'camera.northbar.establish-bay-two-safe',
        durationSeconds: 5,
        transition: 'cut',
        transitionSeconds: 0,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['casual', 'mack', 'della-voss'],
        requiredSubjectIds: ['casual', 'mack', 'della-voss'],
        performanceRequests: [
          performance(
            'performance.northbar.rook-arrival-hold',
            'shot.ash-001.northbar-establish',
            'casual',
            'mack',
            'mark.northbar.rook-coach-step',
          ),
          performance(
            'performance.northbar.mack-clock-hold',
            'shot.ash-001.northbar-establish',
            'mack',
            'casual',
            'mark.northbar.mack-pillar',
          ),
          performance(
            'performance.northbar.della-writing-hold',
            'shot.ash-001.northbar-establish',
            'della-voss',
            'mack',
            'mark.northbar.della-counter',
          ),
        ],
        safeFrame: { minSubjectMarginPercent: 8, narrowFieldOfView: 50 },
      },
      {
        id: 'shot.ash-001.failed-pickup-two-shot',
        purpose:
          'Put Rook and Mack in one credible eyeline before the missing-person reveal.',
        cameraAnchorId: 'camera.northbar.rook-mack-two-shot',
        alternateCameraAnchorId: 'camera.northbar.rook-mack-two-shot-safe',
        durationSeconds: 5.3,
        transition: 'ease',
        transitionSeconds: 0.35,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['casual', 'mack'],
        requiredSubjectIds: ['casual', 'mack'],
        performanceRequests: [
          performance(
            'performance.northbar.rook-listens',
            'shot.ash-001.failed-pickup-two-shot',
            'casual',
            'mack',
            'mark.northbar.rook-curb',
          ),
          performance(
            'performance.northbar.mack-restrained',
            'shot.ash-001.failed-pickup-two-shot',
            'mack',
            'casual',
            'mark.northbar.mack-pillar',
          ),
        ],
        subtitleCues: [
          {
            id: 'subtitle.northbar.rook.where-orin',
            speakerId: 'rook',
            text: 'Orin was supposed to meet me. I have his fee.',
            startSeconds: 0.45,
            endSeconds: 2.45,
          },
          {
            id: 'subtitle.northbar.mack.missed-two-nights',
            speakerId: 'mack',
            text: 'Missed two nights. That is not like him.',
            startSeconds: 2.65,
            endSeconds: 5.05,
          },
        ],
        safeFrame: { minSubjectMarginPercent: 10, narrowFieldOfView: 44 },
      },
      {
        id: 'shot.ash-001.mack-missing-close',
        purpose: 'Hold on Mack long enough to read the cost he is withholding.',
        cameraAnchorId: 'camera.northbar.mack-missing-close',
        alternateCameraAnchorId: 'camera.northbar.mack-missing-close-safe',
        durationSeconds: 4,
        transition: 'cut',
        transitionSeconds: 0,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['mack'],
        requiredSubjectIds: ['mack'],
        performanceRequests: [
          performance(
            'performance.northbar.mack-reaction-hold',
            'shot.ash-001.mack-missing-close',
            'mack',
            'casual',
          ),
        ],
        subtitleCues: [
          {
            id: 'subtitle.northbar.mack.orin-sent-ticket',
            speakerId: 'mack',
            text: 'He sent your ticket. Then he vanished.',
            startSeconds: 0.35,
            endSeconds: 3.75,
          },
        ],
        safeFrame: { minSubjectMarginPercent: 13, narrowFieldOfView: 36 },
      },
      {
        id: 'shot.ash-001.della-carbon-close',
        purpose:
          'Frame Della with the manifest while a level-owned carbon shift motivates Marrow learning the wagon without claiming hand contact.',
        cameraAnchorId: 'camera.northbar.della-carbon-close-safe',
        alternateCameraAnchorId: 'camera.northbar.della-carbon-close-alt',
        durationSeconds: 4.6,
        transition: 'cut',
        transitionSeconds: 0,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['della-voss'],
        requiredSubjectIds: ['della-voss'],
        requiredVisualIds: [
          'prop.northbar.arrival-manifest',
          'prop.northbar.manifest-carbon',
        ],
        performanceRequests: [
          performance(
            'performance.northbar.della-carbon-hold',
            'shot.ash-001.della-carbon-close',
            'della-voss',
            'mack',
          ),
        ],
        subtitleCues: [
          {
            id: 'subtitle.northbar.della.passenger-work',
            speakerId: 'della-voss',
            text: 'Passenger work now, Mack?',
            startSeconds: 1.05,
            endSeconds: 4.25,
          },
        ],
        pathRequests: [
          {
            id: 'path.ash-001.carbon-shift',
            visualIds: ['prop.northbar.manifest-carbon'],
            pointIds: [
              'path.northbar.carbon-start',
              'path.northbar.carbon-shift',
            ],
            startSeconds: 0.8,
            durationSeconds: 1.6,
          },
        ],
        safeFrame: { minSubjectMarginPercent: 14, narrowFieldOfView: 34 },
      },
      {
        id: 'shot.ash-001.della-intercepts',
        purpose:
          'Connect the stolen record, Mack’s wagon, and Rook in one spatial cover.',
        cameraAnchorId: 'camera.northbar.three-way-cover',
        alternateCameraAnchorId: 'camera.northbar.three-way-cover-safe',
        durationSeconds: 4.3,
        transition: 'ease',
        transitionSeconds: 0.3,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['casual', 'mack', 'della-voss'],
        requiredSubjectIds: ['casual', 'mack', 'della-voss'],
        performanceRequests: [
          performance(
            'performance.northbar.rook-alert-hold',
            'shot.ash-001.della-intercepts',
            'casual',
            'della-voss',
          ),
          performance(
            'performance.northbar.mack-misdirect-hold',
            'shot.ash-001.della-intercepts',
            'mack',
            'della-voss',
          ),
        ],
        subtitleCues: [
          {
            id: 'subtitle.northbar.mack.still-service',
            speakerId: 'mack',
            text: 'Still service. Just not yours.',
            startSeconds: 0.45,
            endSeconds: 2.2,
          },
          {
            id: 'subtitle.northbar.della.see-you-junction',
            speakerId: 'della-voss',
            text: 'I know where that wagon sleeps.',
            startSeconds: 2.35,
            endSeconds: 4.1,
          },
        ],
        safeFrame: { minSubjectMarginPercent: 8, narrowFieldOfView: 48 },
      },
      {
        id: 'shot.ash-001.rook-decision-close',
        purpose:
          'Hold on Rook’s guarded reaction long enough to make the coming choice legible without claiming a visible prop inference.',
        cameraAnchorId: 'camera.northbar.rook-decision-close-safe',
        alternateCameraAnchorId: 'camera.northbar.rook-decision-close-alt',
        durationSeconds: 4.8,
        transition: 'cut',
        transitionSeconds: 0,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['casual'],
        requiredSubjectIds: ['casual'],
        performanceRequests: [
          performance(
            'performance.northbar.rook-decision-hold',
            'shot.ash-001.rook-decision-close',
            'casual',
            'della-voss',
          ),
        ],
        safeFrame: { minSubjectMarginPercent: 14, narrowFieldOfView: 36 },
      },
      {
        id: 'shot.ash-001.ticket-choice',
        purpose:
          'Let Rook reject the unused 6:10 and choose Junction through a restrained indication while Mack witnesses the decision.',
        cameraAnchorId: 'camera.northbar.ticket-choice',
        alternateCameraAnchorId: 'camera.northbar.ticket-choice-safe',
        durationSeconds: 4.5,
        transition: 'ease',
        transitionSeconds: 0.25,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['casual', 'mack'],
        requiredSubjectIds: ['casual', 'mack'],
        performanceRequests: [
          performance(
            'performance.northbar.rook-choice-hold',
            'shot.ash-001.ticket-choice',
            'casual',
            'mack',
            'mark.northbar.rook-curb',
            'indicate',
            0.8,
          ),
          performance(
            'performance.northbar.mack-witness-hold',
            'shot.ash-001.ticket-choice',
            'mack',
            'casual',
            'mark.northbar.mack-pillar',
          ),
        ],
        subtitleCues: [
          {
            id: 'subtitle.northbar.rook.junction-then',
            speakerId: 'rook',
            text: 'Junction, then.',
            startSeconds: 1.25,
            endSeconds: 4.1,
          },
        ],
        safeFrame: { minSubjectMarginPercent: 11, narrowFieldOfView: 40 },
      },
      {
        id: 'shot.ash-001.wagon-entry',
        purpose:
          'Use an opaque exterior cut as the service wagon begins moving; make no door, seat, or driving claim.',
        cameraAnchorId: 'camera.northbar.wagon-entry',
        durationSeconds: 4.4,
        transition: 'ease',
        transitionSeconds: 0.35,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: [],
        requiredVisualIds: [
          'vehicle.mack.service-wagon',
          'v.service-wagon-cabin',
          'v.service-wagon-side-stripe',
          'v.service-wagon-roof-beacon',
        ],
        pathRequests: [
          {
            id: 'path.ash-001.wagon-entry',
            visualIds: [
              'vehicle.mack.service-wagon',
              'v.service-wagon-cabin',
              'v.service-wagon-hood',
              'v.service-wagon-windshield',
              'v.service-wagon-bumper',
              'v.service-wagon-side-stripe',
              'v.service-wagon-roof-beacon',
              'v.service-wagon-wheel-front-left',
              'v.service-wagon-wheel-front-right',
              'v.service-wagon-wheel-rear-left',
              'v.service-wagon-wheel-rear-right',
              'service-wagon-body',
            ],
            pointIds: [
              'path.northbar.wagon-exit',
              'path.northbar.wagon-exit-1',
            ],
            startSeconds: 1,
            durationSeconds: 3.2,
          },
        ],
        subtitleCues: [
          {
            id: 'subtitle.northbar.mack.move',
            speakerId: 'mack',
            text: 'Before she finishes the plate.',
            startSeconds: 0.5,
            endSeconds: 3.9,
          },
        ],
        safeFrame: { minSubjectMarginPercent: 8, narrowFieldOfView: 50 },
      },
      {
        id: 'shot.ash-001.wagon-departure',
        purpose:
          'Carry the service wagon behind the authored divider so real destination readiness can take over.',
        cameraAnchorId: 'camera.northbar.wagon-departure',
        durationSeconds: 5.2,
        transition: 'ease',
        transitionSeconds: 0.4,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: [],
        requiredVisualIds: [
          'vehicle.mack.service-wagon',
          'v.service-wagon-cabin',
          'v.service-wagon-side-stripe',
          'v.service-wagon-roof-beacon',
        ],
        pathRequests: [
          {
            id: 'path.ash-001.wagon-departure',
            visualIds: [
              'vehicle.mack.service-wagon',
              'v.service-wagon-cabin',
              'v.service-wagon-hood',
              'v.service-wagon-windshield',
              'v.service-wagon-bumper',
              'v.service-wagon-side-stripe',
              'v.service-wagon-roof-beacon',
              'v.service-wagon-wheel-front-left',
              'v.service-wagon-wheel-front-right',
              'v.service-wagon-wheel-rear-left',
              'v.service-wagon-wheel-rear-right',
              'service-wagon-body',
            ],
            pointIds: [
              'path.northbar.wagon-exit-1',
              'path.northbar.wagon-exit-2',
              'path.northbar.wagon-exit-3',
            ],
            startSeconds: 0,
            durationSeconds: 5,
          },
        ],
        subtitleCues: [
          {
            id: 'subtitle.northbar.mack.route',
            speakerId: 'mack',
            text: 'Signal Corner first. Garage after.',
            startSeconds: 0.65,
            endSeconds: 4.7,
          },
        ],
        safeFrame: { minSubjectMarginPercent: 7, narrowFieldOfView: 52 },
      },
    ],
    destinationShot: {
      id: 'shot.ash-001.junction-arrival',
      purpose:
        'Establish Rook at Junction only after destination readiness, then return exact gameplay ownership.',
      cameraAnchorId: 'camera.ash-001.junction-arrival',
      durationSeconds: 4.8,
      transition: 'ease',
      transitionSeconds: 0.4,
      obstructionPolicy: 'shared-camera-collision',
      participantIds: ['casual'],
      requiredSubjectIds: ['casual'],
      safeFrame: { minSubjectMarginPercent: 8, narrowFieldOfView: 44 },
    },
  },
  {
    id: 'cinematic.ash-001.destination-reveal',
    storyBeatId: 'ash-001-contact-yard-reveal',
    missionId: 'ash-001-walk-the-block',
    participantIds: ['casual'],
    speakerIds: [],
    entryEventId: 'cinematic.ash-001.destination-reveal.entered',
    completionEventId: 'cinematic.ash-001.destination-reveal.completed',
    skipPolicy: 'confirm',
    dependencies: {
      levelId: 'test-district',
      locationId: 'location.ash-001.contact-yard',
      cameraAnchorIds: ['camera.ash-001.contact-reveal'],
      assetIds: [],
      animationIds: [],
      worldFactIds: [],
    },
    restorationPolicy: 'exact-prior-gameplay',
    shots: [
      {
        id: 'shot.ash-001.destination-reveal',
        purpose:
          'Briefly establish the meeting yard and return control without advancing the mission.',
        cameraAnchorId: 'camera.ash-001.contact-reveal',
        durationSeconds: 2.8,
        transition: 'ease',
        transitionSeconds: 0.35,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['casual'],
        safeFrame: { minSubjectMarginPercent: 8, narrowFieldOfView: 50 },
      },
    ],
  },
  {
    id: 'cinematic.ash-001.legacy-opening',
    storyBeatId: 'ash-001-walk-the-block',
    missionId: 'ash-001-walk-the-block',
    participantIds: ['casual', 'mack'],
    speakerIds: ['rook', 'mack'],
    entryEventId: 'cinematic.ash-001.legacy-opening.entered',
    completionEventId: 'cinematic.ash-001.legacy-opening.completed',
    skipPolicy: 'confirm',
    dependencies: {
      levelId: 'test-district',
      locationId: 'landmark.north-approach',
      cameraAnchorIds: [
        'camera.ash-001.north-arrival',
        'camera.ash-001.junction-watch',
        'camera.ash-001.mack-position',
      ],
      assetIds: [],
      animationIds: [],
      worldFactIds: [],
    },
    restorationPolicy: 'exact-prior-gameplay',
    shots: [
      {
        id: 'shot.ash-001.north-arrival',
        purpose:
          'Retain the legacy lifecycle coverage for focused regression tests.',
        cameraAnchorId: 'camera.ash-001.north-arrival',
        durationSeconds: 3.4,
        transition: 'ease',
        transitionSeconds: 0.45,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['casual'],
        subtitle: {
          speakerId: 'mack',
          text: 'You picked a fine morning to be late.',
          startSeconds: 0.35,
          endSeconds: 3.1,
        },
        safeFrame: { minSubjectMarginPercent: 9, narrowFieldOfView: 48 },
      },
      {
        id: 'shot.ash-001.junction-watch',
        purpose: 'Retain the legacy Junction camera regression surface.',
        cameraAnchorId: 'camera.ash-001.junction-watch',
        durationSeconds: 3.2,
        transition: 'ease',
        transitionSeconds: 0.4,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['casual'],
        subtitle: {
          speakerId: 'rook',
          text: 'Junction is watching the north road.',
          startSeconds: 0.3,
          endSeconds: 2.9,
        },
        safeFrame: { minSubjectMarginPercent: 8, narrowFieldOfView: 50 },
      },
      {
        id: 'shot.ash-001.mack-position',
        purpose: 'Retain the legacy Mack camera regression surface.',
        cameraAnchorId: 'camera.ash-001.mack-position',
        durationSeconds: 3.5,
        transition: 'ease',
        transitionSeconds: 0.45,
        obstructionPolicy: 'shared-camera-collision',
        participantIds: ['mack'],
        subtitle: {
          speakerId: 'mack',
          text: 'Garage. West side. Get here without bringing the audience.',
          startSeconds: 0.3,
          endSeconds: 3.25,
        },
        safeFrame: { minSubjectMarginPercent: 10, narrowFieldOfView: 46 },
      },
    ],
  },
] as const satisfies readonly CinematicDefinition[];
